@startuml
left to right direction
skinparam classAttributeIconSize 0
skinparam componentStyle uml2
skinparam actorStyle awesome
hide circle

actor "Sales Employee" as se
actor "Sales Manager" as sm
actor "Sales Officer" as so

rectangle FlightBookingSystem {
  usecase "Search for a Flight" as UC1
  usecase "Create a Flight" as UC2
  usecase "Book Tickets" as UC3
  usecase "Cancel Tickets" as UC10
  usecase "View additional FlightOptions" as UC4
  usecase "Create FlightOptions" as UC5
  usecase "Edit FlightOptions" as UC11
  usecase "Remove FlightOptions" as UC12
  usecase "View KPI's" as UC6
  usecase "Create PriceReductions" as UC7
  usecase "Edit PriceReductions" as UC13
  usecase "Remove PriceReductions" as UC14
  usecase "Start SalesProcess" as UC8
  usecase "Stop SalesProcess" as UC15
  usecase "Create Route" as UC9
  usecase "Edit Route" as UC18
  usecase "Remove Route" as UC19
  usecase "Login" as UC16
  usecase "Logout" as UC17
}

UC2 --|> UC9: <<extends>>
UC2 --|> UC5: <<extends>>

UC3 --|> UC1: <<includes>>
UC3 --|> UC4: <<includes>>
/'
UC11 --|>UC1: <<includes>>
UC12 --|>UC1: <<includes>>
UC13 --|>UC1: <<includes>>
UC14 --|>UC1: <<includes>>
UC7 --|>UC1: <<includes>>'/

se --> UC1
se --> UC3
se --> UC4
se --> UC10
se --> UC16
se --> UC17

so --> UC2
so --> UC5
so --> UC7
so --> UC11
so --> UC12
so --> UC13
so --> UC14
so --> UC8
so --> UC15
so --> UC16
so --> UC17
so --> UC18
so --> UC19

sm --> UC6
sm --> UC16
sm --> UC17
@enduml